export const searchHistory = [
  'Best business development strategies for startups',
  'Top interview questions for BDA intern roles',
  'IQ Matrix project best practices',
  'How to prepare mock interviews',
  'Upcoming business development events in 2024',
  'Top SaaS tools for business development',
  'How to improve lead generation skills',
  'Key trends in business development 2025',
  'How to evaluate BDA intern performance',
  'Effective email outreach templates',
  'Tips for building long-term client relationships',
  'Best CRM tools for small businesses',
  'How to create a sales funnel for startups',
  'Effective cold calling techniques',
  'Examples of successful B2B partnerships',
  'How to set and track KPIs for a sales team',
  'Strategies to upsell to existing customers',
  'Impact of AI on business development',
  'Common mistakes in sales pitch presentations',
  'How to negotiate better deals with clients',
];
