export const GoogleLensResults = [
  {
    type: 'image_match',
    title: 'Vintage Camera',
    description:
      'A classic vintage camera perfect for photography enthusiasts.',
    image_url: 'https://picsum.photos/id/250/600/400',
    source_url: 'https://example.com/vintage-camera',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Handcrafted Wooden Bowl',
    description: 'Beautifully handcrafted wooden bowl ideal for home decor.',
    image_url: 'https://picsum.photos/id/251/600/400',
    source_url: 'https://example.com/wooden-bowl',
    price: '$25.00',
  },
  {
    type: 'webpage',
    title: 'Modern Art Sculpture',
    description:
      'An abstract modern art sculpture to enhance your living space.',
    image_url: 'https://picsum.photos/id/252/600/400',
    source_url: 'https://example.com/art-sculpture',
    price: null,
  },
  {
    type: 'similar_images',
    title: 'Ceramic Vase Collection',
    description: 'A collection of elegant ceramic vases in various designs.',
    image_url: 'https://picsum.photos/id/253/600/400',
    source_url: 'https://example.com/ceramic-vases',
    price: null,
  },
  {
    type: 'image_match',
    title: 'Leather-bound Journal',
    description: 'Premium leather-bound journal for your daily writings.',
    image_url: 'https://picsum.photos/id/254/600/400',
    source_url: 'https://example.com/leather-journal',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Gourmet Coffee Beans',
    description: 'Freshly roasted gourmet coffee beans for the perfect brew.',
    image_url: 'https://picsum.photos/id/255/600/400',
    source_url: 'https://example.com/coffee-beans',
    price: '$15.99',
  },
  {
    type: 'webpage',
    title: 'Handmade Soap Set',
    description: 'A set of organic handmade soaps with natural ingredients.',
    image_url: 'https://picsum.photos/id/256/600/400',
    source_url: 'https://example.com/handmade-soaps',
    price: null,
  },
  {
    type: 'similar_images',
    title: 'Artisan Cheese Platter',
    description: 'A selection of fine artisan cheeses for gourmet lovers.',
    image_url: 'https://picsum.photos/id/257/600/400',
    source_url: 'https://example.com/cheese-platter',
    price: null,
  },
  {
    type: 'image_match',
    title: 'Vintage Vinyl Records',
    description: 'Collection of classic vinyl records for music aficionados.',
    image_url: 'https://picsum.photos/id/258/600/400',
    source_url: 'https://example.com/vinyl-records',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Luxury Silk Scarf',
    description: 'Elegant silk scarf to complement your fashion ensemble.',
    image_url: 'https://picsum.photos/id/259/600/400',
    source_url: 'https://example.com/silk-scarf',
    price: '$45.00',
  },
  {
    type: 'webpage',
    title: 'Antique Pocket Watch',
    description: 'A timeless antique pocket watch with intricate details.',
    image_url: 'https://picsum.photos/id/260/600/400',
    source_url: 'https://example.com/pocket-watch',
    price: null,
  },
  {
    type: 'similar_images',
    title: 'Handwoven Basket',
    description: 'A durable handwoven basket made from natural fibers.',
    image_url: 'https://picsum.photos/id/261/600/400',
    source_url: 'https://example.com/handwoven-basket',
    price: null,
  },
  {
    type: 'image_match',
    title: 'Vintage Camera',
    description:
      'A classic vintage camera perfect for photography enthusiasts.',
    image_url: 'https://picsum.photos/id/250/600/400',
    source_url: 'https://example.com/vintage-camera',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Designer Sunglasses',
    description: 'Stylish designer sunglasses with UV protection.',
    image_url: 'https://picsum.photos/id/263/600/400',
    source_url: 'https://example.com/sunglasses',
    price: '$120.00',
  },
  {
    type: 'webpage',
    title: 'Handcrafted Necklace',
    description: 'Unique handcrafted necklace with semi-precious stones.',
    image_url: 'https://picsum.photos/id/264/600/400',
    source_url: 'https://example.com/necklace',
    price: null,
  },
  {
    type: 'similar_images',
    title: 'Bespoke Leather Wallet',
    description: 'Custom-made leather wallet with personalized engraving.',
    image_url: 'https://picsum.photos/id/265/600/400',
    source_url: 'https://example.com/leather-wallet',
    price: null,
  },
  {
    type: 'image_match',
    title: 'Handcrafted Wooden Toy',
    description: 'Eco-friendly handcrafted wooden toy for children.',
    image_url: 'https://picsum.photos/id/266/600/400',
    source_url: 'https://example.com/wooden-toy',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Luxury Silk Scarf',
    description: 'Elegant silk scarf to complement your fashion ensemble.',
    image_url: 'https://picsum.photos/id/259/600/400',
    source_url: 'https://example.com/silk-scarf',
    price: '$45.00',
  },
  {
    type: 'image_match',
    title: 'Vintage Camera',
    description:
      'A classic vintage camera perfect for photography enthusiasts.',
    image_url: 'https://picsum.photos/id/250/600/400',
    source_url: 'https://example.com/vintage-camera',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Handcrafted Wooden Bowl',
    description: 'Beautifully handcrafted wooden bowl ideal for home decor.',
    image_url: 'https://picsum.photos/id/251/600/400',
    source_url: 'https://example.com/wooden-bowl',
    price: '$25.00',
  },
  {
    type: 'webpage',
    title: 'Modern Art Sculpture',
    description:
      'An abstract modern art sculpture to enhance your living space.',
    image_url: 'https://picsum.photos/id/252/600/400',
    source_url: 'https://example.com/art-sculpture',
    price: null,
  },
  {
    type: 'similar_images',
    title: 'Ceramic Vase Collection',
    description: 'A collection of elegant ceramic vases in various designs.',
    image_url: 'https://picsum.photos/id/253/600/400',
    source_url: 'https://example.com/ceramic-vases',
    price: null,
  },
  {
    type: 'image_match',
    title: 'Leather-bound Journal',
    description: 'Premium leather-bound journal for your daily writings.',
    image_url: 'https://picsum.photos/id/254/600/400',
    source_url: 'https://example.com/leather-journal',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Gourmet Coffee Beans',
    description: 'Freshly roasted gourmet coffee beans for the perfect brew.',
    image_url: 'https://picsum.photos/id/255/600/400',
    source_url: 'https://example.com/coffee-beans',
    price: '$15.99',
  },
  {
    type: 'webpage',
    title: 'Handmade Soap Set',
    description: 'A set of organic handmade soaps with natural ingredients.',
    image_url: 'https://picsum.photos/id/256/600/400',
    source_url: 'https://example.com/handmade-soaps',
    price: null,
  },
  {
    type: 'similar_images',
    title: 'Artisan Cheese Platter',
    description: 'A selection of fine artisan cheeses for gourmet lovers.',
    image_url: 'https://picsum.photos/id/257/600/400',
    source_url: 'https://example.com/cheese-platter',
    price: null,
  },
  {
    type: 'image_match',
    title: 'Vintage Vinyl Records',
    description: 'Collection of classic vinyl records for music aficionados.',
    image_url: 'https://picsum.photos/id/258/600/400',
    source_url: 'https://example.com/vinyl-records',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Luxury Silk Scarf',
    description: 'Elegant silk scarf to complement your fashion ensemble.',
    image_url: 'https://picsum.photos/id/259/600/400',
    source_url: 'https://example.com/silk-scarf',
    price: '$45.00',
  },
  {
    type: 'webpage',
    title: 'Antique Pocket Watch',
    description: 'A timeless antique pocket watch with intricate details.',
    image_url: 'https://picsum.photos/id/260/600/400',
    source_url: 'https://example.com/pocket-watch',
    price: null,
  },
  {
    type: 'similar_images',
    title: 'Handwoven Basket',
    description: 'A durable handwoven basket made from natural fibers.',
    image_url: 'https://picsum.photos/id/261/600/400',
    source_url: 'https://example.com/handwoven-basket',
    price: null,
  },
  {
    type: 'image_match',
    title: 'Vintage Camera',
    description:
      'A classic vintage camera perfect for photography enthusiasts.',
    image_url: 'https://picsum.photos/id/250/600/400',
    source_url: 'https://example.com/vintage-camera',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Designer Sunglasses',
    description: 'Stylish designer sunglasses with UV protection.',
    image_url: 'https://picsum.photos/id/263/600/400',
    source_url: 'https://example.com/sunglasses',
    price: '$120.00',
  },
  {
    type: 'webpage',
    title: 'Handcrafted Necklace',
    description: 'Unique handcrafted necklace with semi-precious stones.',
    image_url: 'https://picsum.photos/id/264/600/400',
    source_url: 'https://example.com/necklace',
    price: null,
  },
  {
    type: 'similar_images',
    title: 'Bespoke Leather Wallet',
    description: 'Custom-made leather wallet with personalized engraving.',
    image_url: 'https://picsum.photos/id/265/600/400',
    source_url: 'https://example.com/leather-wallet',
    price: null,
  },
  {
    type: 'image_match',
    title: 'Handcrafted Wooden Toy',
    description: 'Eco-friendly handcrafted wooden toy for children.',
    image_url: 'https://picsum.photos/id/266/600/400',
    source_url: 'https://example.com/wooden-toy',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Luxury Silk Scarf',
    description: 'Elegant silk scarf to complement your fashion ensemble.',
    image_url: 'https://picsum.photos/id/259/600/400',
    source_url: 'https://example.com/silk-scarf',
    price: '$45.00',
  },
  {
    type: 'image_match',
    title: 'Vintage Camera',
    description:
      'A classic vintage camera perfect for photography enthusiasts.',
    image_url: 'https://picsum.photos/id/250/600/400',
    source_url: 'https://example.com/vintage-camera',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Handcrafted Wooden Bowl',
    description: 'Beautifully handcrafted wooden bowl ideal for home decor.',
    image_url: 'https://picsum.photos/id/251/600/400',
    source_url: 'https://example.com/wooden-bowl',
    price: '$25.00',
  },
  {
    type: 'webpage',
    title: 'Modern Art Sculpture',
    description:
      'An abstract modern art sculpture to enhance your living space.',
    image_url: 'https://picsum.photos/id/252/600/400',
    source_url: 'https://example.com/art-sculpture',
    price: null,
  },
  {
    type: 'similar_images',
    title: 'Ceramic Vase Collection',
    description: 'A collection of elegant ceramic vases in various designs.',
    image_url: 'https://picsum.photos/id/253/600/400',
    source_url: 'https://example.com/ceramic-vases',
    price: null,
  },
  {
    type: 'image_match',
    title: 'Leather-bound Journal',
    description: 'Premium leather-bound journal for your daily writings.',
    image_url: 'https://picsum.photos/id/254/600/400',
    source_url: 'https://example.com/leather-journal',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Gourmet Coffee Beans',
    description: 'Freshly roasted gourmet coffee beans for the perfect brew.',
    image_url: 'https://picsum.photos/id/255/600/400',
    source_url: 'https://example.com/coffee-beans',
    price: '$15.99',
  },
  {
    type: 'webpage',
    title: 'Handmade Soap Set',
    description: 'A set of organic handmade soaps with natural ingredients.',
    image_url: 'https://picsum.photos/id/256/600/400',
    source_url: 'https://example.com/handmade-soaps',
    price: null,
  },
  {
    type: 'similar_images',
    title: 'Artisan Cheese Platter',
    description: 'A selection of fine artisan cheeses for gourmet lovers.',
    image_url: 'https://picsum.photos/id/257/600/400',
    source_url: 'https://example.com/cheese-platter',
    price: null,
  },
  {
    type: 'image_match',
    title: 'Vintage Vinyl Records',
    description: 'Collection of classic vinyl records for music aficionados.',
    image_url: 'https://picsum.photos/id/258/600/400',
    source_url: 'https://example.com/vinyl-records',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Luxury Silk Scarf',
    description: 'Elegant silk scarf to complement your fashion ensemble.',
    image_url: 'https://picsum.photos/id/259/600/400',
    source_url: 'https://example.com/silk-scarf',
    price: '$45.00',
  },
  {
    type: 'webpage',
    title: 'Antique Pocket Watch',
    description: 'A timeless antique pocket watch with intricate details.',
    image_url: 'https://picsum.photos/id/260/600/400',
    source_url: 'https://example.com/pocket-watch',
    price: null,
  },
  {
    type: 'similar_images',
    title: 'Handwoven Basket',
    description: 'A durable handwoven basket made from natural fibers.',
    image_url: 'https://picsum.photos/id/261/600/400',
    source_url: 'https://example.com/handwoven-basket',
    price: null,
  },
  {
    type: 'image_match',
    title: 'Vintage Camera',
    description:
      'A classic vintage camera perfect for photography enthusiasts.',
    image_url: 'https://picsum.photos/id/250/600/400',
    source_url: 'https://example.com/vintage-camera',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Designer Sunglasses',
    description: 'Stylish designer sunglasses with UV protection.',
    image_url: 'https://picsum.photos/id/263/600/400',
    source_url: 'https://example.com/sunglasses',
    price: '$120.00',
  },
  {
    type: 'webpage',
    title: 'Handcrafted Necklace',
    description: 'Unique handcrafted necklace with semi-precious stones.',
    image_url: 'https://picsum.photos/id/264/600/400',
    source_url: 'https://example.com/necklace',
    price: null,
  },
  {
    type: 'similar_images',
    title: 'Bespoke Leather Wallet',
    description: 'Custom-made leather wallet with personalized engraving.',
    image_url: 'https://picsum.photos/id/265/600/400',
    source_url: 'https://example.com/leather-wallet',
    price: null,
  },
  {
    type: 'image_match',
    title: 'Handcrafted Wooden Toy',
    description: 'Eco-friendly handcrafted wooden toy for children.',
    image_url: 'https://picsum.photos/id/266/600/400',
    source_url: 'https://example.com/wooden-toy',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Luxury Silk Scarf',
    description: 'Elegant silk scarf to complement your fashion ensemble.',
    image_url: 'https://picsum.photos/id/259/600/400',
    source_url: 'https://example.com/silk-scarf',
    price: '$45.00',
  },
  {
    type: 'image_match',
    title: 'Vintage Camera',
    description:
      'A classic vintage camera perfect for photography enthusiasts.',
    image_url: 'https://picsum.photos/id/250/600/400',
    source_url: 'https://example.com/vintage-camera',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Handcrafted Wooden Bowl',
    description: 'Beautifully handcrafted wooden bowl ideal for home decor.',
    image_url: 'https://picsum.photos/id/251/600/400',
    source_url: 'https://example.com/wooden-bowl',
    price: '$25.00',
  },
  {
    type: 'webpage',
    title: 'Modern Art Sculpture',
    description:
      'An abstract modern art sculpture to enhance your living space.',
    image_url: 'https://picsum.photos/id/252/600/400',
    source_url: 'https://example.com/art-sculpture',
    price: null,
  },
  {
    type: 'similar_images',
    title: 'Ceramic Vase Collection',
    description: 'A collection of elegant ceramic vases in various designs.',
    image_url: 'https://picsum.photos/id/253/600/400',
    source_url: 'https://example.com/ceramic-vases',
    price: null,
  },
  {
    type: 'image_match',
    title: 'Leather-bound Journal',
    description: 'Premium leather-bound journal for your daily writings.',
    image_url: 'https://picsum.photos/id/254/600/400',
    source_url: 'https://example.com/leather-journal',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Gourmet Coffee Beans',
    description: 'Freshly roasted gourmet coffee beans for the perfect brew.',
    image_url: 'https://picsum.photos/id/255/600/400',
    source_url: 'https://example.com/coffee-beans',
    price: '$15.99',
  },
  {
    type: 'webpage',
    title: 'Handmade Soap Set',
    description: 'A set of organic handmade soaps with natural ingredients.',
    image_url: 'https://picsum.photos/id/256/600/400',
    source_url: 'https://example.com/handmade-soaps',
    price: null,
  },
  {
    type: 'similar_images',
    title: 'Artisan Cheese Platter',
    description: 'A selection of fine artisan cheeses for gourmet lovers.',
    image_url: 'https://picsum.photos/id/257/600/400',
    source_url: 'https://example.com/cheese-platter',
    price: null,
  },
  {
    type: 'image_match',
    title: 'Vintage Vinyl Records',
    description: 'Collection of classic vinyl records for music aficionados.',
    image_url: 'https://picsum.photos/id/258/600/400',
    source_url: 'https://example.com/vinyl-records',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Luxury Silk Scarf',
    description: 'Elegant silk scarf to complement your fashion ensemble.',
    image_url: 'https://picsum.photos/id/259/600/400',
    source_url: 'https://example.com/silk-scarf',
    price: '$45.00',
  },
  {
    type: 'webpage',
    title: 'Antique Pocket Watch',
    description: 'A timeless antique pocket watch with intricate details.',
    image_url: 'https://picsum.photos/id/260/600/400',
    source_url: 'https://example.com/pocket-watch',
    price: null,
  },
  {
    type: 'similar_images',
    title: 'Handwoven Basket',
    description: 'A durable handwoven basket made from natural fibers.',
    image_url: 'https://picsum.photos/id/261/600/400',
    source_url: 'https://example.com/handwoven-basket',
    price: null,
  },
  {
    type: 'image_match',
    title: 'Vintage Camera',
    description:
      'A classic vintage camera perfect for photography enthusiasts.',
    image_url: 'https://picsum.photos/id/250/600/400',
    source_url: 'https://example.com/vintage-camera',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Designer Sunglasses',
    description: 'Stylish designer sunglasses with UV protection.',
    image_url: 'https://picsum.photos/id/263/600/400',
    source_url: 'https://example.com/sunglasses',
    price: '$120.00',
  },
  {
    type: 'webpage',
    title: 'Handcrafted Necklace',
    description: 'Unique handcrafted necklace with semi-precious stones.',
    image_url: 'https://picsum.photos/id/264/600/400',
    source_url: 'https://example.com/necklace',
    price: null,
  },
  {
    type: 'similar_images',
    title: 'Bespoke Leather Wallet',
    description: 'Custom-made leather wallet with personalized engraving.',
    image_url: 'https://picsum.photos/id/265/600/400',
    source_url: 'https://example.com/leather-wallet',
    price: null,
  },
  {
    type: 'image_match',
    title: 'Handcrafted Wooden Toy',
    description: 'Eco-friendly handcrafted wooden toy for children.',
    image_url: 'https://picsum.photos/id/266/600/400',
    source_url: 'https://example.com/wooden-toy',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Luxury Silk Scarf',
    description: 'Elegant silk scarf to complement your fashion ensemble.',
    image_url: 'https://picsum.photos/id/259/600/400',
    source_url: 'https://example.com/silk-scarf',
    price: '$45.00',
  },
  {
    type: 'image_match',
    title: 'Vintage Camera',
    description:
      'A classic vintage camera perfect for photography enthusiasts.',
    image_url: 'https://picsum.photos/id/250/600/400',
    source_url: 'https://example.com/vintage-camera',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Handcrafted Wooden Bowl',
    description: 'Beautifully handcrafted wooden bowl ideal for home decor.',
    image_url: 'https://picsum.photos/id/251/600/400',
    source_url: 'https://example.com/wooden-bowl',
    price: '$25.00',
  },
  {
    type: 'webpage',
    title: 'Modern Art Sculpture',
    description:
      'An abstract modern art sculpture to enhance your living space.',
    image_url: 'https://picsum.photos/id/252/600/400',
    source_url: 'https://example.com/art-sculpture',
    price: null,
  },
  {
    type: 'similar_images',
    title: 'Ceramic Vase Collection',
    description: 'A collection of elegant ceramic vases in various designs.',
    image_url: 'https://picsum.photos/id/253/600/400',
    source_url: 'https://example.com/ceramic-vases',
    price: null,
  },
  {
    type: 'image_match',
    title: 'Leather-bound Journal',
    description: 'Premium leather-bound journal for your daily writings.',
    image_url: 'https://picsum.photos/id/254/600/400',
    source_url: 'https://example.com/leather-journal',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Gourmet Coffee Beans',
    description: 'Freshly roasted gourmet coffee beans for the perfect brew.',
    image_url: 'https://picsum.photos/id/255/600/400',
    source_url: 'https://example.com/coffee-beans',
    price: '$15.99',
  },
  {
    type: 'webpage',
    title: 'Handmade Soap Set',
    description: 'A set of organic handmade soaps with natural ingredients.',
    image_url: 'https://picsum.photos/id/256/600/400',
    source_url: 'https://example.com/handmade-soaps',
    price: null,
  },
  {
    type: 'similar_images',
    title: 'Artisan Cheese Platter',
    description: 'A selection of fine artisan cheeses for gourmet lovers.',
    image_url: 'https://picsum.photos/id/257/600/400',
    source_url: 'https://example.com/cheese-platter',
    price: null,
  },
  {
    type: 'image_match',
    title: 'Vintage Vinyl Records',
    description: 'Collection of classic vinyl records for music aficionados.',
    image_url: 'https://picsum.photos/id/258/600/400',
    source_url: 'https://example.com/vinyl-records',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Luxury Silk Scarf',
    description: 'Elegant silk scarf to complement your fashion ensemble.',
    image_url: 'https://picsum.photos/id/259/600/400',
    source_url: 'https://example.com/silk-scarf',
    price: '$45.00',
  },
  {
    type: 'webpage',
    title: 'Antique Pocket Watch',
    description: 'A timeless antique pocket watch with intricate details.',
    image_url: 'https://picsum.photos/id/260/600/400',
    source_url: 'https://example.com/pocket-watch',
    price: null,
  },
  {
    type: 'similar_images',
    title: 'Handwoven Basket',
    description: 'A durable handwoven basket made from natural fibers.',
    image_url: 'https://picsum.photos/id/261/600/400',
    source_url: 'https://example.com/handwoven-basket',
    price: null,
  },
  {
    type: 'image_match',
    title: 'Vintage Camera',
    description:
      'A classic vintage camera perfect for photography enthusiasts.',
    image_url: 'https://picsum.photos/id/250/600/400',
    source_url: 'https://example.com/vintage-camera',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Designer Sunglasses',
    description: 'Stylish designer sunglasses with UV protection.',
    image_url: 'https://picsum.photos/id/263/600/400',
    source_url: 'https://example.com/sunglasses',
    price: '$120.00',
  },
  {
    type: 'webpage',
    title: 'Handcrafted Necklace',
    description: 'Unique handcrafted necklace with semi-precious stones.',
    image_url: 'https://picsum.photos/id/264/600/400',
    source_url: 'https://example.com/necklace',
    price: null,
  },
  {
    type: 'similar_images',
    title: 'Bespoke Leather Wallet',
    description: 'Custom-made leather wallet with personalized engraving.',
    image_url: 'https://picsum.photos/id/265/600/400',
    source_url: 'https://example.com/leather-wallet',
    price: null,
  },
  {
    type: 'image_match',
    title: 'Handcrafted Wooden Toy',
    description: 'Eco-friendly handcrafted wooden toy for children.',
    image_url: 'https://picsum.photos/id/266/600/400',
    source_url: 'https://example.com/wooden-toy',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Luxury Silk Scarf',
    description: 'Elegant silk scarf to complement your fashion ensemble.',
    image_url: 'https://picsum.photos/id/259/600/400',
    source_url: 'https://example.com/silk-scarf',
    price: '$45.00',
  },
  {
    type: 'image_match',
    title: 'Vintage Camera',
    description:
      'A classic vintage camera perfect for photography enthusiasts.',
    image_url: 'https://picsum.photos/id/250/600/400',
    source_url: 'https://example.com/vintage-camera',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Handcrafted Wooden Bowl',
    description: 'Beautifully handcrafted wooden bowl ideal for home decor.',
    image_url: 'https://picsum.photos/id/251/600/400',
    source_url: 'https://example.com/wooden-bowl',
    price: '$25.00',
  },
  {
    type: 'webpage',
    title: 'Modern Art Sculpture',
    description:
      'An abstract modern art sculpture to enhance your living space.',
    image_url: 'https://picsum.photos/id/252/600/400',
    source_url: 'https://example.com/art-sculpture',
    price: null,
  },
  {
    type: 'similar_images',
    title: 'Ceramic Vase Collection',
    description: 'A collection of elegant ceramic vases in various designs.',
    image_url: 'https://picsum.photos/id/253/600/400',
    source_url: 'https://example.com/ceramic-vases',
    price: null,
  },
  {
    type: 'image_match',
    title: 'Leather-bound Journal',
    description: 'Premium leather-bound journal for your daily writings.',
    image_url: 'https://picsum.photos/id/254/600/400',
    source_url: 'https://example.com/leather-journal',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Gourmet Coffee Beans',
    description: 'Freshly roasted gourmet coffee beans for the perfect brew.',
    image_url: 'https://picsum.photos/id/255/600/400',
    source_url: 'https://example.com/coffee-beans',
    price: '$15.99',
  },
  {
    type: 'webpage',
    title: 'Handmade Soap Set',
    description: 'A set of organic handmade soaps with natural ingredients.',
    image_url: 'https://picsum.photos/id/256/600/400',
    source_url: 'https://example.com/handmade-soaps',
    price: null,
  },
  {
    type: 'similar_images',
    title: 'Artisan Cheese Platter',
    description: 'A selection of fine artisan cheeses for gourmet lovers.',
    image_url: 'https://picsum.photos/id/257/600/400',
    source_url: 'https://example.com/cheese-platter',
    price: null,
  },
  {
    type: 'image_match',
    title: 'Vintage Vinyl Records',
    description: 'Collection of classic vinyl records for music aficionados.',
    image_url: 'https://picsum.photos/id/258/600/400',
    source_url: 'https://example.com/vinyl-records',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Luxury Silk Scarf',
    description: 'Elegant silk scarf to complement your fashion ensemble.',
    image_url: 'https://picsum.photos/id/259/600/400',
    source_url: 'https://example.com/silk-scarf',
    price: '$45.00',
  },
  {
    type: 'webpage',
    title: 'Antique Pocket Watch',
    description: 'A timeless antique pocket watch with intricate details.',
    image_url: 'https://picsum.photos/id/260/600/400',
    source_url: 'https://example.com/pocket-watch',
    price: null,
  },
  {
    type: 'similar_images',
    title: 'Handwoven Basket',
    description: 'A durable handwoven basket made from natural fibers.',
    image_url: 'https://picsum.photos/id/261/600/400',
    source_url: 'https://example.com/handwoven-basket',
    price: null,
  },
  {
    type: 'image_match',
    title: 'Vintage Camera',
    description:
      'A classic vintage camera perfect for photography enthusiasts.',
    image_url: 'https://picsum.photos/id/250/600/400',
    source_url: 'https://example.com/vintage-camera',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Designer Sunglasses',
    description: 'Stylish designer sunglasses with UV protection.',
    image_url: 'https://picsum.photos/id/263/600/400',
    source_url: 'https://example.com/sunglasses',
    price: '$120.00',
  },
  {
    type: 'webpage',
    title: 'Handcrafted Necklace',
    description: 'Unique handcrafted necklace with semi-precious stones.',
    image_url: 'https://picsum.photos/id/264/600/400',
    source_url: 'https://example.com/necklace',
    price: null,
  },
  {
    type: 'similar_images',
    title: 'Bespoke Leather Wallet',
    description: 'Custom-made leather wallet with personalized engraving.',
    image_url: 'https://picsum.photos/id/265/600/400',
    source_url: 'https://example.com/leather-wallet',
    price: null,
  },
  {
    type: 'image_match',
    title: 'Handcrafted Wooden Toy',
    description: 'Eco-friendly handcrafted wooden toy for children.',
    image_url: 'https://picsum.photos/id/266/600/400',
    source_url: 'https://example.com/wooden-toy',
    price: null,
  },
  {
    type: 'shopping',
    title: 'Luxury Silk Scarf',
    description: 'Elegant silk scarf to complement your fashion ensemble.',
    image_url: 'https://picsum.photos/id/259/600/400',
    source_url: 'https://example.com/silk-scarf',
    price: '$45.00',
  },
];
